name: enviloup-videos

services:
  nginx:
    image: nginx:stable-alpine3.19
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - enviloup

  api:
    image: enviloup/api
    networks:
      - enviloup

  users:
    image: enviloup/users
    networks:
      - enviloup

  comments:
    image: enviloup/comments
    networks:
      - enviloup

  notifications:
    image: enviloup/notifications
    networks:
      - enviloup

  processing:
    image: enviloup/processing
    networks:
      - enviloup

  recommendations:
    image: enviloup/recommendations
    networks:
      - enviloup

  search:
    image: enviloup/search
    networks:
      - enviloup

  uploading:
    image: enviloup/uploading
    networks:
      - enviloup

networks:
  enviloup:
