name: enviloup-videos

services:
  nginx:
    image: tiangolo/nginx-rtmp
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/var/www/html
    networks:
      - enviloup

  s3-storage:
    image: minio/minio
    command: minio server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKET=enviloup
    networks:
      - enviloup

  api:
    image: enviloup/api
    networks:
      - enviloup
    expose:
      - 8000

  users:
    image: enviloup/users
    networks:
      - enviloup
    expose:
      - 8000

  comments:
    image: enviloup/comments
    networks:
      - enviloup
    expose:
      - 8000

  notifications:
    image: enviloup/notifications
    networks:
      - enviloup
    expose:
      - 8000

  processing:
    image: enviloup/processing
    networks:
      - enviloup
    expose:
      - 8000

  recommendations:
    image: enviloup/recommendations
    networks:
      - enviloup
    expose:
      - 8000

  search:
    image: enviloup/search
    networks:
      - enviloup
    expose:
      - 8000

  uploading:
    image: enviloup/uploading
    networks:
      - enviloup
    expose:
      - 8000

networks:
  enviloup:

volumes:
  minio_data:
